name: Update Stats

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past every 6th hour from 3 through 23 (UTC+0)
    - cron: '0 3/6 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Fill Table With New Stats
        run: pnpm run update-stats-day

      - uses: EndBug/add-and-commit@v7
        with:
          add: 'covid_stats.csv'
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
